train:
  _target_: src.datasets.LJspeechDataset
  part: train
  limit: 1
  max_audio_length: 8192
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LJspeechDataset
  part: train
  limit: 1
  max_audio_length: 8192
  instance_transforms: ${transforms.instance_transforms.train}
